### PR TITLE
Fix package XML mappings

### LINKED ISSUE #48: Incorrect generated .gitignore on package repository types
Version 3.0.4

Installing packages directly from connect causes the generated .gitignore entries to be prepended with `/.`, like this `/./app/etc/modules/Shiptheory_Interlinkst.xml`

Here's my composer.json

```
{
    "name": "aydinhassan/magento-skeleton",
    "description": "A Magento Skeleton Application",
    "require-dev": {
        "ecomdev/ecomdev_phpunit": "~0.3",
        "mikey179/vfsStream": "~1.5"
    },
    "require": {
        "magento-hackathon/magento-composer-installer": "~3.0",
        "wearejh/magento-composer-autoloader": "1.0.1",
        "aydin-hassan/magento-core-composer-installer": "1.2.3",
        "magento/magento": "~1.9.2",
        "connect20/shiptheory_interlinkst": "0.0.1"
    },
    "authors": [
        {
            "name": "Aydin Hassan",
            "email": "aydin@wearejh.com"
        }
    ],
    "repositories": [
        {
            "type": "composer",
            "url": "http://packages.firegento.com"
        },
        {
            "type": "git",
            "url": "git@github.com:WeareJH/magento-composer-autoloader.git"
        },
        {
            "type": "git",
            "url": "git@github.com:AydinHassan/magento-community.git"
        },
        {
            "url": "https://github.com/EcomDev/EcomDev_PHPUnit",
            "type": "git"
        },
        {
            "type": "vcs",
            "url": "https://github.com/AydinHassan/magento-core-installer.git"
        },
        {
            "type": "package",
            "package": {
                "name": "connect20/shiptheory_interlinkst",
                "version": "0.0.1",
                "dist": {
                    "type": "tar",
                    "url": "http://connect20.magentocommerce.com/community/Shiptheory_Interlinkst/0.0.1/Shiptheory_Interlinkst-0.0.1.tgz",
                    "reference": null,
                    "shasum": null
                },
                "type": "magento-module",
                "extra": {
                    "package-xml": "package.xml"
                }
            }
        }
    ],
    "extra":{
        "magento-root-dir": "htdocs/",
        "magento-force": true,
        "with-bootstrap-patch": false,
        "auto-append-gitignore": true,
        "skip-suggest-repositories": true
    }
}
```

### PR DESCRIPTION
**Pull request by AydinHassan**
Package XMl mappings have `./` prepended to them, because the base paths from `res/target.xml` are prepended to each mapping. This causes issues when updating the `gitignore` as the `gitignore` prepends `/` to the paths. This results in a path like `/./app/code/community/EcomDev/PHPUnitTest` in the `gitignore`. The fix as I see it is to just remove the first 2 characters of the file path from the mappings generated by `\MagentoHackathon\Composer\Magento\Parser\PackageXmlParser`. 

Fixes #48

### CODE REVIEW

**Comment by Flyingmana** [comment]
:+1:

**Comment by AydinHassan** [comment]
ping @nevvermind  Hi, can you review these couple of PR's I created if you have a free minute?

**Comment by nevvermind** [comment]
Dunno about you guys, but I'm feeling better knowing that we have a very strict ignore path, avoiding possible "carpet-ignoring" - in this regard, can you try using a leading fw-slash in the gitignore fie, @AydinHassan ? Like this: 
```
$ cat app/.gitignore
/app/code/community/EcomDev/PHPUnitTest
```
Quote from the docs: 
```
A leading slash matches the beginning of the pathname. 
For example, "/*.c" matches "cat-file.c" but not "mozilla-sha1/sha1.c".
```
It's improbable to have the _exact_ same path (`a/b/c`) somewhere in the codebase, but I don't really care. I'd rather we have good ignore patterns.

Also, that 2 in `substr` looks worryingly hardcoded. What about doing 
```php
"/" . preg_replace('#^[\/\.]*#', '', $relativePath)
``` 
on every path?

:exclamation: If none of the above, please add a changelog entry.

**Comment by AydinHassan** [comment]
Hey @nevvermind A fw-slash is always on all the paths in the `gitginore` as during the deploy process, mappings are converted to the absolute path. When adding adding a deployed file in this [function](https://github.com/Cotya/magento-composer-installer/blob/3.0/src/MagentoHackathon/Composer/Magento/Deploystrategy/DeploystrategyAbstract.php#L485) the magento root dir is stripped off, leaving the path with a fw-slash at the beginning. The magent-root-dir is passed into the deploy-strategy with the trailing slash stripped off. 

I can explicitly add a fw-slash in the `GitIgnore` class if it doesn't exist, as I do agree the intention isn't clear?

I agree with the hard-coding it's just that the base-paths are loaded from [target.xml](https://github.com/Cotya/magento-composer-installer/blob/3.0/res/target.xml) which have `./` pre-pended to them, however, it's no problem adding the check you proposed, if maybe `target.xml` changes.

**Comment by AydinHassan** [comment]
@nevvermind @Flyingmana Incorporated suggestions and added a change-log entry

File: src/MagentoHackathon/Composer/Magento/Parser/PackageXmlParser.php [hunk 1]
```diff
@@ -64,6 +64,8 @@ protected function parseMappings()
                     foreach ($target->children() as $child) {
                         foreach ($this->getElementPaths($child) as $elementPath) {
                             $relativePath = $basePath . '/' . $elementPath;
+                            //remove the any trailing './' or '.' from the targets base-path.
+                            $relativePath = preg_replace('#^[\/\.]*#', '', $relativePath);
```
Comment (nevvermind) [inline src/MagentoHackathon/Composer/Magento/Parser/PackageXmlParser.php]: You've got the same preg_replace in three different places. We should try putting this in a separate method.

Comment (AydinHassan) [inline src/MagentoHackathon/Composer/Magento/Parser/PackageXmlParser.php]: They are not exactly the same, what do you suggest without introducing another dependency? Maybe we can just wrap the ones in `GitIgnore` into a private method?

Comment (nevvermind) [inline src/MagentoHackathon/Composer/Magento/Parser/PackageXmlParser.php]: Ah, right, they're not the same. Yeah, a private in `GitIgnore` sounds good.

Comment (AydinHassan) [inline src/MagentoHackathon/Composer/Magento/Parser/PackageXmlParser.php]: It didn't really need to be a `preg_match` anyway. `ltrim` will suffice, I've still moved it to a private method

**Comment by AydinHassan** [comment]
It didn't really need to be a `preg_match` anyway. I've changed to `ltrim` and moved to a private method.

**Comment by nevvermind** [comment]
looks good.
